services:

  kafka-dev:
    image: avcaliani/kafka-in-docker
    container_name: kafka-dev
    ports:
      - 9092:9092
  
  log-service:
    image: kafka-app-services
    container_name: log-service
    build: .
    depends_on:
      - kafka-dev
    command: make delayed-start log-service
  
  email-service:
    image: kafka-app-services
    container_name: email-service
    build: .
    depends_on:
      - kafka-dev
    command: make delayed-start email-service
  
  fraud-service:
    image: kafka-app-services
    container_name: fraud-service
    build: .
    depends_on:
      - kafka-dev
    command: make delayed-start fraud-service

  order-service:
    image: kafka-app-services
    container_name: order-service
    build: .
    depends_on:
      - kafka-dev
    ports:
      - 8000:8000
    command: make delayed-start order-service
  
  user-service:
    image: kafka-app-services
    container_name: user-service
    build: .
    depends_on:
      - kafka-dev
    command: make delayed-start user-service