services:

  kafka:
    image: kafka-dev
    container_name: kafka
    build: ./kafka
    ports:
      - 9092:9092 # Kafka
      - 2181:2181 # Zookeeper
  
  log-service:
    image: kafka-app-services
    container_name: log-service
    build: .
    depends_on:
      - kafka
    command: make delayed-start log-service
  
  email-service:
    image: kafka-app-services
    container_name: email-service
    build: .
    depends_on:
      - kafka
    command: make delayed-start email-service
  
  fraud-service:
    image: kafka-app-services
    container_name: fraud-service
    build: .
    depends_on:
      - kafka
    command: make delayed-start fraud-service

  order-service:
    image: kafka-app-services
    container_name: order-service
    build: .
    depends_on:
      - kafka
    ports:
      - 8000:8000
    command: make delayed-start order-service
  
  user-service:
    image: kafka-app-services
    container_name: user-service
    build: .
    depends_on:
      - kafka
    command: make delayed-start user-service